//
// Created by 郭珂桢 on 2024/5/23.
//

#ifndef MINECRAFT_WORLDCONSTANTS_H
#define MINECRAFT_WORLDCONSTANTS_H

constexpr int CHUNK_SIZE = 16, CHUNK_AREA = CHUNK_SIZE * CHUNK_SIZE,
    CHUNK_VOLUME = CHUNK_SIZE * CHUNK_AREA,
    WATER_LEVEL = 64;

#endif //MINECRAFT_WORLDCONSTANTS_H
